// <auto-generated />
using System;
using BioDesk.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BioDesk.Data.Migrations
{
    [DbContext(typeof(BioDeskContext))]
    [Migration("20250927071207_CorrigirCamposDecimais")]
    partial class CorrigirCamposDecimais
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.8");

            modelBuilder.Entity("BioDesk.Domain.Entities.Consulta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DataConsulta")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataUltimaEdicao")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notas")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("PacienteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Prescricao")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoConsulta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Valor")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("DataConsulta")
                        .HasDatabaseName("IX_Consulta_DataConsulta");

                    b.HasIndex("PacienteId")
                        .HasDatabaseName("IX_Consulta_PacienteId");

                    b.ToTable("Consultas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DataConsulta = new DateTime(2025, 9, 13, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataCriacao = new DateTime(2025, 9, 13, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            Notas = "Primeira consulta de naturopatia. Paciente apresenta sintomas de stress.",
                            PacienteId = 1,
                            Status = "Realizada",
                            TipoConsulta = "Primeira",
                            Valor = 60.00m
                        },
                        new
                        {
                            Id = 2,
                            DataConsulta = new DateTime(2025, 9, 20, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataCriacao = new DateTime(2025, 9, 20, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            Notas = "Seguimento - melhoria dos sintomas de stress.",
                            PacienteId = 1,
                            Status = "Realizada",
                            TipoConsulta = "Seguimento",
                            Valor = 45.00m
                        },
                        new
                        {
                            Id = 3,
                            DataConsulta = new DateTime(2025, 9, 17, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataCriacao = new DateTime(2025, 9, 17, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            Notas = "Primeira consulta de osteopatia. Dores lombares.",
                            PacienteId = 2,
                            Status = "Realizada",
                            TipoConsulta = "Primeira",
                            Valor = 65.00m
                        },
                        new
                        {
                            Id = 4,
                            DataConsulta = new DateTime(2025, 9, 29, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataCriacao = new DateTime(2025, 9, 24, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            Notas = "Consulta agendada para medicina quântica.",
                            PacienteId = 3,
                            Status = "Agendada",
                            TipoConsulta = "Primeira",
                            Valor = 70.00m
                        },
                        new
                        {
                            Id = 5,
                            DataConsulta = new DateTime(2025, 9, 22, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataCriacao = new DateTime(2025, 9, 19, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            Notas = "Primeira consulta naturopática. Avaliação stress laboral.",
                            PacienteId = 4,
                            Status = "Realizada",
                            TipoConsulta = "Primeira",
                            Valor = 65.00m
                        },
                        new
                        {
                            Id = 6,
                            DataConsulta = new DateTime(2025, 9, 30, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataCriacao = new DateTime(2025, 9, 25, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            Notas = "Seguimento - avaliar progresso do tratamento para ansiedade.",
                            PacienteId = 4,
                            Status = "Agendada",
                            TipoConsulta = "Seguimento",
                            Valor = 50.00m
                        },
                        new
                        {
                            Id = 7,
                            DataConsulta = new DateTime(2025, 10, 7, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataCriacao = new DateTime(2025, 9, 26, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            Notas = "Reavaliação geral e ajuste de tratamento.",
                            PacienteId = 4,
                            Status = "Agendada",
                            TipoConsulta = "Seguimento",
                            Valor = 50.00m
                        });
                });

            modelBuilder.Entity("BioDesk.Domain.Entities.Paciente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AjustesTratamento")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Alergias")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("AlergiasConhecidas")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Altura")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("AmplitudeMovimento")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AntecedentesFamiliares")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AtividadeFisica")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("TEXT");

                    b.Property<string>("AuralEnergetica")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvaliacacaoChakras")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("AvaliacaoPostural")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("BloqueiosEnergeticos")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CirurgiasAnteriores")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("CirurgiasRealizadas")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumoAgua")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumoAlcool")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ConsumoAlcoolEnum")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ContatoEmergencia")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DataNascimento")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DiagnosticoEnergetico")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoencasAnteriores")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DoencasHereditarias")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("DuracaoSintomas")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoChakraPrincipal")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoCivil")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("EstadoMeridianos")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExerciciosRecomendados")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("FatoresDesencadeantes")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("FrequenciaCardiaca")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("FrequenciaSessoes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FrequenciasDetectadas")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<bool>("Fumador")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Genero")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("GestaoStress")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HabitosAlimentares")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoriaDoencaAtual")
                        .HasMaxLength(3000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoricoMedicoFamiliar")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoricoMedicoPessoal")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("HistoricoTraumas")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("InicioSintomas")
                        .HasColumnType("TEXT");

                    b.Property<string>("IntensidadeSintomas")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("IntoleranciasAlimentares")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MedicacaoAtual")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Morada")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("MudancasEstiloVida")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("NIF")
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NivelAtividadeFisica")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NivelStress")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NivelVitalidade")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NotasSessoes")
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<int?>("NumeroSessoesRealizadas")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ObjetivosTratamento")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesExameFisico")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ObservacoesGerais")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("OutrosHabitos")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PadroesAlimentares")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PalpacaoTecidual")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PatternSono")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Peso")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("PontosTensao")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosturaPrincipal")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PressaoDiastolica")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("PressaoSistolica")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Profissao")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgressoSintomas")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProtocolosNaturopaticos")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ProximaConsulta")
                        .HasColumnType("TEXT");

                    b.Property<string>("QualidadeDesonoEnum")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("QualidadeSono")
                        .HasColumnType("INTEGER");

                    b.Property<string>("QueixaPrincipal")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("ResultadosTestes")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SintomasPrincipais")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SintomasSecundarios")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SistemaCardiovascular")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SistemaDigestivo")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SistemaNeurologico")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SistemaRespiratorio")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuplementacaoRecomendada")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("SuplementosAtuais")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Tabagismo")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TelefoneEmergencia")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("TerapiasComplementares")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestesEnergeticos")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TestesOrtopedicos")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoExercicio")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("TratamentosOsteopaticos")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("TratamentosRealizados")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UltimaSessao")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique()
                        .HasDatabaseName("IX_Paciente_Unique");

                    b.ToTable("Pacientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AtualizadoEm = new DateTime(2025, 9, 25, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            CriadoEm = new DateTime(2025, 8, 28, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataNascimento = new DateTime(1985, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "ana.silva@email.com",
                            Fumador = false,
                            NIF = "",
                            Nome = "Ana Silva",
                            Telefone = "912345678"
                        },
                        new
                        {
                            Id = 2,
                            AtualizadoEm = new DateTime(2025, 9, 22, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            CriadoEm = new DateTime(2025, 9, 2, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataNascimento = new DateTime(1990, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "joao.ferreira@email.com",
                            Fumador = false,
                            NIF = "",
                            Nome = "João Ferreira",
                            Telefone = "925678912"
                        },
                        new
                        {
                            Id = 3,
                            AtualizadoEm = new DateTime(2025, 9, 26, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            CriadoEm = new DateTime(2025, 9, 7, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataNascimento = new DateTime(1988, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "maria.costa@email.com",
                            Fumador = false,
                            NIF = "",
                            Nome = "Maria Costa",
                            Telefone = "934567823"
                        },
                        new
                        {
                            Id = 4,
                            AtualizadoEm = new DateTime(2025, 9, 26, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            CriadoEm = new DateTime(2025, 9, 12, 8, 12, 7, 93, DateTimeKind.Local).AddTicks(5146),
                            DataNascimento = new DateTime(1975, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DuracaoSintomas = "6 meses",
                            Email = "carlos.teste@email.com",
                            EstadoCivil = "Casado",
                            Fumador = false,
                            Genero = "M",
                            HistoriaDoencaAtual = "Episódios frequentes de ansiedade relacionados com pressão no trabalho",
                            IntensidadeSintomas = "Moderada",
                            NIF = "",
                            Nome = "Carlos Teste",
                            Profissao = "Engenheiro",
                            QueixaPrincipal = "Stress e ansiedade laboral",
                            Telefone = "967891234"
                        });
                });

            modelBuilder.Entity("BioDesk.Domain.Entities.Consulta", b =>
                {
                    b.HasOne("BioDesk.Domain.Entities.Paciente", "Paciente")
                        .WithMany("Consultas")
                        .HasForeignKey("PacienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Paciente");
                });

            modelBuilder.Entity("BioDesk.Domain.Entities.Paciente", b =>
                {
                    b.Navigation("Consultas");
                });
#pragma warning restore 612, 618
        }
    }
}
