using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using BioDesk.Domain.Entities;
using BioDesk.Domain.Enums;

namespace BioDesk.Data.SeedData;

public static class ItemBancoCoreSeeder
{
    public static List<ItemBancoCore> GetAll()
    {
        var items = new List<ItemBancoCore>();
        items.AddRange(GetFloraisBach());
        items.AddRange(GetChakras());
        items.AddRange(GetMeridianos());
        items.AddRange(GetOrgaos());

        // IDs will be auto-generated by EF Core when SaveChanges() is called
        return items;
    }

    private static Guid DeterministicGuid(string scope, string name)
    {
        var normalized = $"{scope}|{name}".Trim().ToUpperInvariant();
        var bytes = Encoding.UTF8.GetBytes(normalized);
        var hash = SHA256.HashData(bytes);
        var guidBytes = new byte[16];
        Array.Copy(hash, guidBytes, 16);
        return new Guid(guidBytes);
    }

    private static ItemBancoCore Create(CategoriaCore categoria, string nome, string subcategoria, string descricaoBreve, object metadata, string fonteOrigem, string genero = "Ambos")
    {
        return new ItemBancoCore
        {
            ExternalId = DeterministicGuid(categoria.ToString(), nome),
            Nome = nome,
            Categoria = categoria,
            Subcategoria = subcategoria,
            DescricaoBreve = descricaoBreve,
            JsonMetadata = JsonSerializer.Serialize(metadata),
            FonteOrigem = fonteOrigem,
            GeneroAplicavel = genero,
            IsActive = true,
            CreatedAt = DateTime.UtcNow
        };
    }

    private static List<ItemBancoCore> GetFloraisBach()
    {
        var fonte = "Dr. Edward Bach – The Twelve Healers and Other Remedies (1933)";
        var data = new (string Nome, string Grupo, string Desc, string[] Indic, string[] Afirms, string[] Combos)[]
        {
            ("Rock Rose","Medo","Para pânico e terror intenso; útil em emergências emocionais e pesadelos, promovendo coragem e calma.",
                new[]{"Pânico","Terror","Emergências","Pesadelos"}, new[]{"Estou em segurança","Confio na vida"}, new[]{"Star of Bethlehem","Cherry Plum","Mimulus"}),
            ("Mimulus","Medo","Para medos concretos e conhecidos (fobias, timidez, ansiedade social); incentiva coragem tranquila no dia a dia.",
                new[]{"Medos concretos","Timidez","Fobias","Ansiedade social"}, new[]{"Enfrento com serenidade","A coragem habita em mim"}, new[]{"Walnut","Rock Rose"}),
            ("Cherry Plum","Medo","Para medo de perder o controlo e impulsos; promove autocontenção e clareza mental serena.",
                new[]{"Medo de perder controlo","Impulsos","Pensamentos intrusivos"}, new[]{"Eu domino a minha mente","A tranquilidade guia as minhas ações"}, new[]{"White Chestnut","Rock Rose"}),
            ("Aspen","Medo","Para ansiedades vagas e pressentimentos; fortalece confiança e proteção interior perante o desconhecido.",
                new[]{"Ansiedade vaga","Pressentimentos","Sensibilidade psíquica"}, new[]{"Confio na vida","Sinto-me protegido"}, new[]{"Walnut","Rock Rose"}),
            ("Red Chestnut","Medo","Para preocupação excessiva com os outros; desenvolve confiança, desapego amoroso e fé no processo alheio.",
                new[]{"Preocupação pelos outros","Ansiedade por familiares","Apego"}, new[]{"Confio nos caminhos dos outros","Amor com desapego"}, new[]{"Walnut","Elm"}),

            ("Cerato","Incerteza","Para dúvida de si e busca de validação externa; fortalece confiança no próprio julgamento e intuição.",
                new[]{"Dúvida","Procura de conselhos","Insegurança"}, new[]{"Confio no meu sentir","Decido com lucidez"}, new[]{"Scleranthus","Wild Oat"}),
            ("Scleranthus","Incerteza","Para indecisão e oscilações; promove equilíbrio interno e decisão firme e consistente.",
                new[]{"Indecisão","Oscilação","Inconstância"}, new[]{"Escolho com clareza","Equilíbrio e foco"}, new[]{"Cerato","Gentian"}),
            ("Gentian","Incerteza","Para desânimo após contrariedades; incentiva perseverança, visão positiva e confiança no progresso.",
                new[]{"Desânimo","Frustração","Desmotivação"}, new[]{"Sigo confiante","Aprendo com os desafios"}, new[]{"Gorse","Hornbeam"}),
            ("Gorse","Incerteza","Para desesperança extrema; reaviva a fé e a possibilidade de novos caminhos.",
                new[]{"Desesperança","Ceticismo","Desistência"}, new[]{"A esperança renasce em mim","Novas oportunidades surgem"}, new[]{"Gentian","Wild Oat"}),
            ("Hornbeam","Incerteza","Para cansaço mental e procrastinação; restaura motivação, ânimo e frescor para iniciar tarefas.",
                new[]{"Cansaço mental","Procrastinação","Falta de ânimo"}, new[]{"Tenho energia para começar","Faço o que é preciso"}, new[]{"Olive","Gentian"}),
            ("Wild Oat","Incerteza","Para incerteza sobre rumo de vida; promove clareza de propósito, direção e realização pessoal.",
                new[]{"Incerteza vocacional","Falta de direção","Insatisfação"}, new[]{"Conheço o meu caminho","Avanço com propósito"}, new[]{"Cerato","Scleranthus"}),

            ("Clematis","Desinteresse","Para devaneio e distração; traz presença, enraizamento e aplicação criativa.",
                new[]{"Sonhador","Desatenção","Desligamento"}, new[]{"Estou presente","Trago sonhos à realidade"}, new[]{"Walnut","Hornbeam"}),
            ("Honeysuckle","Desinteresse","Para apego ao passado; favorece presença, aceitação e avanço sereno.",
                new[]{"Saudosismo","Nostalgia","Dificuldade em seguir"}, new[]{"Acolho o presente","Sigo em frente"}, new[]{"Star of Bethlehem","Walnut"}),
            ("Wild Rose","Desinteresse","Para resignação e apatia; desperta entusiasmo, interesse pela vida e participação ativa.",
                new[]{"Apatia","Resignação","Desmotivação"}, new[]{"Apaixono-me pela vida","Participo do meu caminho"}, new[]{"Hornbeam","Mustard"}),
            ("Olive","Desinteresse","Para exaustão física e mental após esforços; recupera vitalidade e energia sustentável.",
                new[]{"Exaustão","Cansaço extremo","Burnout"}, new[]{"Renovo a minha energia","Cuido do meu ritmo"}, new[]{"Hornbeam","Elm"}),
            ("White Chestnut","Desinteresse","Para pensamentos repetitivos; promove serenidade mental, foco e clareza.",
                new[]{"Pensamentos obsessivos","Insónia mental","Ruminância"}, new[]{"A mente aquieta","Tenho clareza"}, new[]{"Vervain","Cherry Plum"}),
            ("Mustard","Desinteresse","Para tristeza profunda sem causa; traz estabilidade emocional e luz interior.",
                new[]{"Tristeza sem motivo","Melancolia","Oscilações"}, new[]{"Sou luz e equilíbrio","A alegria me preenche"}, new[]{"Gentian","Wild Rose"}),
            ("Chestnut Bud","Desinteresse","Para repetição de erros; favorece observação, integração e crescimento.",
                new[]{"Repetição de padrões","Desatenção","Aprendizagem superficial"}, new[]{"Aprendo com atenção","Integro cada experiência"}, new[]{"White Chestnut","Clematis"}),

            ("Water Violet","Solidão","Para reserva excessiva e distanciamento; inspira humildade, abertura afetiva e sociabilidade natural.",
                new[]{"Isolamento","Orgulho","Reserva"}, new[]{"Aproximo-me com humildade","Sou acolhedor"}, new[]{"Heather","Holly"}),
            ("Impatiens","Solidão","Para impaciência e irritabilidade; favorece tolerância, ritmo harmonioso e cooperação.",
                new[]{"Impaciência","Irritabilidade","Pressa"}, new[]{"Respeito meu ritmo","Sou paciente"}, new[]{"Vervain","White Chestnut"}),
            ("Heather","Solidão","Para egocentrismo e carência; encoraja empatia, escuta ativa e interesse genuíno pelo outro.",
                new[]{"Autocentramento","Carência","Tagarelice"}, new[]{"Ouço com presença","Interesso-me pelo outro"}, new[]{"Water Violet","Agrimony"}),

            ("Agrimony","Hipersensibilidade","Para quem oculta sofrimento por trás de um sorriso; promove autenticidade emocional e paz.",
                new[]{"Mascara alegria","Ansiedade interna","Evasão"}, new[]{"Expresso-me com verdade","Aceito minhas emoções"}, new[]{"Holly","Walnut"}),
            ("Centaury","Hipersensibilidade","Para dificuldade em dizer não; fortalece assertividade, limites saudáveis e serviço equilibrado.",
                new[]{"Submissão","Dizer não","Falta de limites"}, new[]{"Respeito meus limites","Sirvo com equilíbrio"}, new[]{"Walnut","Vine"}),
            ("Walnut","Hipersensibilidade","Para proteção em mudanças; ajuda a romper padrões e manter-se fiel ao próprio caminho.",
                new[]{"Mudanças","Influências externas","Transições"}, new[]{"Sigo firme na mudança","Protejo meu campo"}, new[]{"Rock Water","Aspen"}),
            ("Holly","Hipersensibilidade","Para raiva, inveja e ciúme; desperta amor, compaixão e abertura do coração.",
                new[]{"Raiva","Ciúme","Inveja"}, new[]{"Acolho o amor","Sou compassivo"}, new[]{"Water Violet","Agrimony"}),

            ("Larch","Desespero","Para falta de autoconfiança e inferioridade; encoraja tentativa, coragem e realização de potenciais.",
                new[]{"Falta de confiança","Comparação","Autoboicote"}, new[]{"Sou capaz","Confio nos meus talentos"}, new[]{"Elm","Gentian"}),
            ("Pine","Desespero","Para culpa e autoacusação; promove perdão, autoaceitação e responsabilidade equilibrada.",
                new[]{"Culpa","Auto-recriminação","Remorso"}, new[]{"Perdoo-me","Aprendo e sigo"}, new[]{"Crab Apple","Star of Bethlehem"}),
            ("Elm","Desespero","Para sobrecarga e responsabilidades excessivas; restaura confiança, organização e senso de capacidade.",
                new[]{"Sobrecarga","Excesso de responsabilidade","Cansaço"}, new[]{"Dou um passo de cada vez","Sou competente"}, new[]{"Hornbeam","Oak"}),
            ("Sweet Chestnut","Desespero","Para angústia extrema; abre espaço para rendição, esperança e renovação interior.",
                new[]{"Angústia extrema","Desespero","Luto profundo"}, new[]{"A esperança surge","Rendo-me ao que é"}, new[]{"Gorse","Star of Bethlehem"}),
            ("Star of Bethlehem","Desespero","Para traumas e choques; atua como consolação e reorganização do campo.",
                new[]{"Trauma","Choque","Luto"}, new[]{"Sou consolado","Integro as experiências"}, new[]{"Rock Rose","Rescue Remedy"}),
            ("Willow","Desespero","Para ressentimento e vitimismo; promove responsabilidade, gratidão e reconciliação com a vida.",
                new[]{"Ressentimento","Amargura","Vitimismo"}, new[]{"Escolho agradecer","Sou coautor da minha vida"}, new[]{"Holly","Beech"}),
            ("Oak","Desespero","Para perseverança além dos limites; resgata descanso, flexibilidade e autocuidado.",
                new[]{"Não parar","Teimosia","Esforço excessivo"}, new[]{"Equilibro esforço e descanso","Respeito meus limites"}, new[]{"Elm","Olive"}),
            ("Crab Apple","Desespero","Para sensação de impureza; favorece aceitação do corpo e purificação equilibrada.",
                new[]{"Purificação","Autoimagem","Limpeza"}, new[]{"Aceito meu corpo","Sou puro e completo"}, new[]{"Pine","Walnut"}),

            ("Chicory","Preocupação excessiva","Para apego possessivo e amor controlador; traz amor altruísta, desapego e generosidade.",
                new[]{"Amor possessivo","Controle","Apego"}, new[]{"Amo com liberdade","Confio e solto"}, new[]{"Holly","Red Chestnut"}),
            ("Vervain","Preocupação excessiva","Para excesso de zelo e tensão; favorece relaxamento, moderação e respeito pelos ritmos.",
                new[]{"Tensão","Excesso de esforço","Idealismo rígido"}, new[]{"Relaxo e confio","Respeito limites naturais"}, new[]{"Impatiens","Rock Water"}),
            ("Vine","Preocupação excessiva","Para atitudes autoritárias; desperta liderança compassiva e escuta do coletivo.",
                new[]{"Autoritarismo","Rigidez","Dominância"}, new[]{"Lidero com empatia","Sirvo ao bem comum"}, new[]{"Beech","Centaury"}),
            ("Beech","Preocupação excessiva","Para intolerância e crítica; estimula compreensão, aceitação e visão amorosa das diferenças.",
                new[]{"Intolerância","Crítica","Impaciência com o outro"}, new[]{"Vejo com benevolência","Aceito o diverso"}, new[]{"Willow","Holly"}),
            ("Rock Water","Preocupação excessiva","Para rigidez consigo mesmo; traz flexibilidade, prazer e espontaneidade saudável.",
                new[]{"Rigidez","Auto-repressão","Perfeccionismo"}, new[]{"Sou flexível","Honro minhas necessidades"}, new[]{"Vervain","Walnut"}),
        };

        var items = new List<ItemBancoCore>(data.Length);
        foreach (var d in data)
        {
            items.Add(Create(
                CategoriaCore.FloraisBach,
                d.Nome,
                d.Grupo,
                d.Desc,
                new { Grupo = d.Grupo, IndicacoesPrincipais = d.Indic, AfirmacoesPositivas = d.Afirms, CombinacoesSugeridas = d.Combos, CompatibilidadeGenero = "Ambos" },
                fonte
            ));
        }
        return items;
    }
    private static List<ItemBancoCore> GetChakras()
    {
        var fonte = "Sistema Védico dos Chakras (tradicional)";
        var items = new List<ItemBancoCore>();

        var principais = new[]
        {
            new { Nome = "Chakra Raiz (Muladhara)",   Num = 1, Cor = "Vermelho",  Elem = "Terra",    Mantra = "LAM",  Desc = "Base da coluna; sobrevivência, segurança e enraizamento vital.", Orgaos = new[]{"Suprarrenais","Rins","Coluna"} },
            new { Nome = "Chakra Sacral (Svadhisthana)", Num = 2, Cor = "Laranja",   Elem = "Água",     Mantra = "VAM",  Desc = "Baixo ventre; fluidez emocional, criatividade e sexualidade saudável.", Orgaos = new[]{"Ovários/Testículos","Bexiga","Quadris"} },
            new { Nome = "Chakra Plexo Solar (Manipura)", Num = 3, Cor = "Amarelo",   Elem = "Fogo",     Mantra = "RAM",  Desc = "Região do estômago; poder pessoal, digestão e autodisciplina.", Orgaos = new[]{"Fígado","Pâncreas","Estômago"} },
            new { Nome = "Chakra Cardíaco (Anahata)",     Num = 4, Cor = "Verde",     Elem = "Ar",       Mantra = "YAM",  Desc = "Centro do peito; amor, compaixão, perdão e equilíbrio relacional.", Orgaos = new[]{"Coração","Pulmões","Timo"} },
            new { Nome = "Chakra Laríngeo (Vishuddha)",   Num = 5, Cor = "Azul",      Elem = "Éter",     Mantra = "HAM",  Desc = "Garganta; comunicação autêntica, expressão e escuta consciente.", Orgaos = new[]{"Tiroide","Cordas vocais","Traqueia"} },
            new { Nome = "Chakra Terceiro Olho (Ajna)",    Num = 6, Cor = "Índigo",    Elem = "Luz",      Mantra = "OM",   Desc = "Testa; intuição, visão e discernimento mental.", Orgaos = new[]{"Hipófise","Olhos","Sistema nervoso"} },
            new { Nome = "Chakra Coroa (Sahasrara)",       Num = 7, Cor = "Violeta/Branco", Elem = "Consciência", Mantra = "AUM", Desc = "Topo da cabeça; transcendência, unidade e espiritualidade.", Orgaos = new[]{"Pineal","Cérebro"} },
        };
        foreach (var c in principais)
        {
            items.Add(Create(
                CategoriaCore.Chakra,
                c.Nome,
                "Principal",
                c.Desc,
                new { Numero = c.Num, Cor = c.Cor, Elemento = c.Elem, MantraBija = c.Mantra, OrgaosRelacionados = c.Orgaos },
                fonte
            ));
        }

        string[] pares =
        {
            "Chakra dos Pés (Esquerdo)", "Chakra dos Pés (Direito)",
            "Chakra dos Joelhos (Esquerdo)", "Chakra dos Joelhos (Direito)",
            "Chakra das Palmas (Mão Esquerda)", "Chakra das Palmas (Mão Direita)",
            "Chakra dos Cotovelos (Esquerdo)", "Chakra dos Cotovelos (Direito)",
            "Chakra dos Ombros (Esquerdo)", "Chakra dos Ombros (Direito)",
            "Chakra dos Ouvidos (Esquerdo)", "Chakra dos Ouvidos (Direito)",
            "Chakra dos Olhos (Esquerdo)", "Chakra dos Olhos (Direito)"
        };
        foreach (var nome in pares)
        {
            items.Add(Create(
                CategoriaCore.Chakra,
                nome,
                "Secundário",
                $"Centro energético secundário em {nome.Replace("Chakra ", string.Empty)}; auxilia equilíbrio local e fluxo periférico.",
                new { Tipo = "Secundário", Area = nome, Suportes = new[] { "Respiração", "Cristais", "Toque consciente" } },
                fonte
            ));
        }

        var singulares = new (string Nome, string Loc, string[] Funcoes)[]
        {
            ("Chakra Alta Major (Nuca)", "Nuca (base do crânio)", new[]{"Integração sensorial","Fluxo craniano","Estado de alerta"}),
            ("Chakra do Timo", "Esterno superior", new[]{"Imunidade","Integração emocional","Vitalidade"}),
            ("Chakra do Baço", "Hipocôndrio esquerdo", new[]{"Metabolismo","Vigor","Purificação sanguínea"}),
            ("Chakra Lunar (Plexo Esquerdo)", "Plexo esquerdo", new[]{"Receptividade","Introspeção","Arrefecimento"}),
            ("Chakra Solar (Plexo Direito)", "Plexo direito", new[]{"Ação","Calor","Iniciativa"}),
            ("Chakra dos Quadris (Esquerdo)", "Quadril esquerdo", new[]{"Mobilidade","Estabilidade","Suporte pélvico"}),
            ("Chakra dos Quadris (Direito)", "Quadril direito", new[]{"Equilíbrio","Força lateral","Alinhamento pélvico"}),
        };
        foreach (var s in singulares)
        {
            items.Add(Create(
                CategoriaCore.Chakra,
                s.Nome,
                "Secundário",
                $"Centro energético secundário em {s.Loc}; suporte funcional complementar e regulação sutil.",
                new { Tipo = "Secundário", Localizacao = s.Loc, Funcoes = s.Funcoes },
                fonte
            ));
        }

        return items;
    }
    private static List<ItemBancoCore> GetMeridianos()
    {
        var fonte = "Medicina Tradicional Chinesa (clássica)";
        var items = new List<ItemBancoCore>();

        // 12 principais
        items.Add(Create(CategoriaCore.Meridiano, "Pulmão (Shou Tai Yin)", "Principal",
            "Meridiano yin do elemento Metal; 03h-05h. Respiração, pele e tristeza quando desequilibrado.",
            new { NomePinyin = "Shou Tai Yin", ElementoMTC = "Metal", HorarioMaximoQi = "03h-05h", Polaridade = "Yin", PontosPrincipais = new[] { "P1 Zhongfu", "P7 Lieque", "P9 Taiyuan" }, OrgaoAcoplado = "Intestino Grosso" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Intestino Grosso (Shou Yang Ming)", "Principal",
            "Meridiano yang do Metal; 05h-07h. Eliminação, pele e capacidade de soltar.",
            new { NomePinyin = "Shou Yang Ming", ElementoMTC = "Metal", HorarioMaximoQi = "05h-07h", Polaridade = "Yang", PontosPrincipais = new[] { "IG4 Hegu", "IG11 Quchi" }, OrgaoAcoplado = "Pulmão" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Estômago (Zu Yang Ming)", "Principal",
            "Meridiano yang da Terra; 07h-09h. Digestão, assimilação e energia pós-natal.",
            new { NomePinyin = "Zu Yang Ming", ElementoMTC = "Terra", HorarioMaximoQi = "07h-09h", Polaridade = "Yang", PontosPrincipais = new[] { "E36 Zusanli", "E40 Fenglong" }, OrgaoAcoplado = "Baço-Pâncreas" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Baço-Pâncreas (Zu Tai Yin)", "Principal",
            "Meridiano yin da Terra; 09h-11h. Transformação e transporte; músculos e umidade.",
            new { NomePinyin = "Zu Tai Yin", ElementoMTC = "Terra", HorarioMaximoQi = "09h-11h", Polaridade = "Yin", PontosPrincipais = new[] { "BP3 Taibai", "BP6 Sanyinjiao" }, OrgaoAcoplado = "Estômago" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Coração (Shou Shao Yin)", "Principal",
            "Meridiano yin do Fogo; 11h-13h. Shen, sono e alegria de viver.",
            new { NomePinyin = "Shou Shao Yin", ElementoMTC = "Fogo", HorarioMaximoQi = "11h-13h", Polaridade = "Yin", PontosPrincipais = new[] { "C7 Shenmen", "C5 Tongli" }, OrgaoAcoplado = "Intestino Delgado" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Intestino Delgado (Shou Tai Yang)", "Principal",
            "Meridiano yang do Fogo; 13h-15h. Separa o puro do impuro; absorção.",
            new { NomePinyin = "Shou Tai Yang", ElementoMTC = "Fogo", HorarioMaximoQi = "13h-15h", Polaridade = "Yang", PontosPrincipais = new[] { "ID3 Houxi", "ID6 Yanglao" }, OrgaoAcoplado = "Coração" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Bexiga (Zu Tai Yang)", "Principal",
            "Meridiano yang da Água; 15h-17h. Dor lombar, eliminação de líquidos e superfície defensiva.",
            new { NomePinyin = "Zu Tai Yang", ElementoMTC = "Água", HorarioMaximoQi = "15h-17h", Polaridade = "Yang", PontosPrincipais = new[] { "B23 Shenshu", "B40 Weizhong" }, OrgaoAcoplado = "Rim" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Rim (Zu Shao Yin)", "Principal",
            "Meridiano yin da Água; 17h-19h. Essência (Jing), ossos e vitalidade.",
            new { NomePinyin = "Zu Shao Yin", ElementoMTC = "Água", HorarioMaximoQi = "17h-19h", Polaridade = "Yin", PontosPrincipais = new[] { "R3 Taixi", "R1 Yongquan" }, OrgaoAcoplado = "Bexiga" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Pericárdio (Shou Jue Yin)", "Principal",
            "Meridiano yin do Fogo; 19h-21h. Protege o coração; circulação e emoção.",
            new { NomePinyin = "Shou Jue Yin", ElementoMTC = "Fogo", HorarioMaximoQi = "19h-21h", Polaridade = "Yin", PontosPrincipais = new[] { "PC6 Neiguan", "PC7 Daling" }, OrgaoAcoplado = "Triplo Aquecedor" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Triplo Aquecedor (Shou Shao Yang)", "Principal",
            "Meridiano yang do Fogo; 21h-23h. Coordena aquecedores, fluidos e homeostase energética.",
            new { NomePinyin = "Shou Shao Yang", ElementoMTC = "Fogo", HorarioMaximoQi = "21h-23h", Polaridade = "Yang", PontosPrincipais = new[] { "TA5 Waiguan", "TA17 Yifeng" }, OrgaoAcoplado = "Pericárdio" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Vesícula Biliar (Zu Shao Yang)", "Principal",
            "Meridiano yang da Madeira; 23h-01h. Decisão, coragem e fluxo de bile.",
            new { NomePinyin = "Zu Shao Yang", ElementoMTC = "Madeira", HorarioMaximoQi = "23h-01h", Polaridade = "Yang", PontosPrincipais = new[] { "VB34 Yanglingquan", "VB20 Fengchi" }, OrgaoAcoplado = "Fígado" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Fígado (Zu Jue Yin)", "Principal",
            "Meridiano yin da Madeira; 01h-03h. Fluxo do Qi, visão, tendões e irritabilidade quando estagnado.",
            new { NomePinyin = "Zu Jue Yin", ElementoMTC = "Madeira", HorarioMaximoQi = "01h-03h", Polaridade = "Yin", PontosPrincipais = new[] { "F3 Taichong", "F8 Ququan" }, OrgaoAcoplado = "Vesícula Biliar" }, fonte));

        // 8 extraordinários
        items.Add(Create(CategoriaCore.Meridiano, "Vaso Governador (Du Mai)", "Extraordinário",
            "Governa os meridianos yang; estabiliza eixo posterior e nutre cérebro.",
            new { Funcoes = new[] { "Governa Yang", "Estabiliza coluna", "Nutre cérebro" }, PontosPrincipais = new[] { "VG4 Mingmen", "VG20 Baihui" }, Polaridade = "Yang" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Vaso Concepção (Ren Mai)", "Extraordinário",
            "Governa os meridianos yin; linha média anterior, fluidos e fertilidade.",
            new { Funcoes = new[] { "Governa Yin", "Nutre útero", "Regula fluidos" }, PontosPrincipais = new[] { "RM4 Guanyuan", "RM17 Shanzhong" }, Polaridade = "Yin" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Chong Mai", "Extraordinário",
            "Mar dos doze meridianos; sangue, nutrição e estabilidade emocional profunda.",
            new { Funcoes = new[] { "Mar do sangue", "Fertilidade", "Nutrição" }, PontosPrincipais = new[] { "RM1 Huiyin", "R3 Taixi", "BP4 Gongsun" }, Polaridade = "Yin predominante" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Dai Mai", "Extraordinário",
            "Vaso cinturão; harmoniza subida/descida do Qi e estabiliza lombar/pélvis.",
            new { Funcoes = new[] { "Cinturão energético", "Harmoniza fluxos", "Estabiliza lombar" }, PontosPrincipais = new[] { "VB26 Daimai", "VB27 Wushu" }, Polaridade = "Yang moderado" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Yang Wei Mai", "Extraordinário",
            "Vaso de ligação Yang; integra meridianos yang e protege superfície.",
            new { Funcoes = new[] { "Liga Yang", "Protege exterior", "Integra circulação Yang" }, PontosPrincipais = new[] { "TA5 Waiguan", "VB15 Toulinqi" }, Polaridade = "Yang" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Yin Wei Mai", "Extraordinário",
            "Vaso de ligação Yin; integra meridianos yin e estabiliza interior emocional.",
            new { Funcoes = new[] { "Liga Yin", "Estabiliza interior", "Nutrição profunda" }, PontosPrincipais = new[] { "PC6 Neiguan", "BP4 Gongsun" }, Polaridade = "Yin" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Yang Qiao Mai", "Extraordinário",
            "Vaso de mobilidade Yang; equilíbrio lateral, olhos e estado de vigília.",
            new { Funcoes = new[] { "Mobilidade Yang", "Equilíbrio lateral", "Vigília" }, PontosPrincipais = new[] { "B62 Shenmai", "IG15 Jianyu" }, Polaridade = "Yang" }, fonte));
        items.Add(Create(CategoriaCore.Meridiano, "Yin Qiao Mai", "Extraordinário",
            "Vaso de mobilidade Yin; influencia introspeção, sono e alinhamento medial.",
            new { Funcoes = new[] { "Mobilidade Yin", "Sono", "Alinhamento medial" }, PontosPrincipais = new[] { "R6 Zhaohai", "R8 Jiaoxin" }, Polaridade = "Yin" }, fonte));

        return items;
    }
    private static List<ItemBancoCore> GetOrgaos()
    {
        var fonte = "Gray's Anatomy; Atlas de Anatomia Humana (Netter)";
        var data = new (string Nome, string Subcat, string Desc, object Meta, string Genero)[]
        {
            // Sistema Nervoso
            ("Cérebro","Sistema Nervoso","Órgão central do sistema nervoso; integra funções cognitivas, emocionais e motoras, regulando o organismo.", new { Sistema = "Nervoso", Funcoes = new[]{"Cognição","Memória","Coordenação"} }, "Ambos"),
            ("Cerebelo","Sistema Nervoso","Coordena equilíbrio, postura e precisão de movimentos finos; modula aprendizagem motora.", new { Sistema = "Nervoso", Funcoes = new[]{"Equilíbrio","Coordenação fina","Aprendizagem"} }, "Ambos"),
            ("Tronco Encefálico","Sistema Nervoso","Regula funções vitais automáticas (respiração, batimentos, vigília) e conecta cérebro/medula.", new { Sistema = "Nervoso", Funcoes = new[]{"Respiração","Cardiorrespiratório","Vigília"} }, "Ambos"),
            ("Medula Espinhal","Sistema Nervoso","Via principal de condução nervosa; reflexos e coordenação segmentar.", new { Sistema = "Nervoso", Funcoes = new[]{"Condução nervosa","Reflexos"} }, "Ambos"),

            // Sentidos/Tegumentar
            ("Olhos","Órgãos dos Sentidos","Responsáveis pela visão; sensíveis à pressão, perfusão e glicemia.", new { Sistema = "Sensorial", Funcoes = new[]{"Visão","Foco","Percepção de luz"} }, "Ambos"),
            ("Ouvidos","Órgãos dos Sentidos","Audição e equilíbrio (vestibular); transmitem sons e sinalizam aceleração.", new { Sistema = "Sensorial", Funcoes = new[]{"Audição","Equilíbrio"} }, "Ambos"),
            ("Nariz","Órgãos dos Sentidos","Olfato e condicionamento do ar inspirado; filtragem imunológica.", new { Sistema = "Respiratório", Funcoes = new[]{"Olfato","Filtragem","Aquecimento do ar"} }, "Ambos"),
            ("Língua","Órgãos dos Sentidos","Paladar, mastigação auxiliar e fala; indicador digestivo segundo MTC.", new { Sistema = "Digestivo", Funcoes = new[]{"Paladar","Fonação","Mastigação"} }, "Ambos"),
            ("Pele","Tegumentar","Maior órgão do corpo; barreira, termorregulação e interface sensorial.", new { Sistema = "Tegumentar", Funcoes = new[]{"Barreira","Termorregulação","Tato"} }, "Ambos"),

            // Respiratório
            ("Faringe","Sistema Respiratório","Conduto aéreo e digestivo; participa de deglutição e ressonância vocal.", new { Sistema = "Respiratório", Funcoes = new[]{"Deglutição","Passagem de ar"} }, "Ambos"),
            ("Laringe","Sistema Respiratório","Contém cordas vocais; protege vias aéreas e permite fonação.", new { Sistema = "Respiratório", Funcoes = new[]{"Fonação","Proteção aérea"} }, "Ambos"),
            ("Traqueia","Sistema Respiratório","Tubo condutor de ar para brônquios; cartilagens anelares mantêm pérvia.", new { Sistema = "Respiratório", Funcoes = new[]{"Condução de ar"} }, "Ambos"),
            ("Brônquios","Sistema Respiratório","Distribuem ar aos pulmões; modulam resistência das vias aéreas.", new { Sistema = "Respiratório", Funcoes = new[]{"Distribuição de ar","Resposta brônquica"} }, "Ambos"),
            ("Pulmões","Sistema Respiratório","Troca gasosa essencial (O2/CO2); sensíveis a inflamação e poluição.", new { Sistema = "Respiratório", Funcoes = new[]{"Hematose","Equilíbrio ácido-base"} }, "Ambos"),
            ("Diafragma","Sistema Respiratório","Músculo respiratório principal; mobilidade coordena pressão e postura.", new { Sistema = "Respiratório", Funcoes = new[]{"Inspiração","Estabilização postural"} }, "Ambos"),

            // Cardiovascular/Linfático/Hematopoético
            ("Coração","Sistema Cardiovascular","Bomba central da circulação; mantém perfusão tecidual e ritmo coordenado.", new { Sistema = "Cardiovascular", Funcoes = new[]{"Bomba sanguínea","Ritmo"} }, "Ambos"),
            ("Baço","Sistema Linfático","Filtra sangue, participa da imunidade e recicla eritrócitos.", new { Sistema = "Linfático", Funcoes = new[]{"Filtragem","Imunidade","Reservatório"} }, "Ambos"),
            ("Timo","Sistema Linfático","Órgão linfóide; maturação de linfócitos T e regulação imunitária.", new { Sistema = "Linfático", Funcoes = new[]{"Maturação linfócitos T","Imunorregulação"} }, "Ambos"),
            ("Gânglios Linfáticos","Sistema Linfático","Estações de filtragem e vigilância imunitária distribuídas pelo corpo.", new { Sistema = "Linfático", Funcoes = new[]{"Filtragem","Resposta imune"} }, "Ambos"),
            ("Medula Óssea","Sistema Hematopoético","Tecido hematopoiético; produz células sanguíneas e dá suporte imunológico.", new { Sistema = "Hematopoético", Funcoes = new[]{"Hematopoiese"} }, "Ambos"),

            // Endócrino
            ("Hipófise (Pituitária)","Sistema Endócrino","Glândula mestra hormonal; regula tiroide, adrenais e gónadas (eixos).", new { Sistema = "Endócrino", Funcoes = new[]{"Regulação hormonal","Eixos HPA/HPG"} }, "Ambos"),
            ("Pineal","Sistema Endócrino","Glândula associada à melatonina; regula ritmos circadianos e qualidade do sono.", new { Sistema = "Endócrino", Funcoes = new[]{"Ritmo circadiano","Sono"} }, "Ambos"),
            ("Tiroide","Sistema Endócrino","Regula metabolismo basal e energia; sensível a iodo e autoimunidade.", new { Sistema = "Endócrino", Funcoes = new[]{"Metabolismo","Termorregulação"} }, "Ambos"),
            ("Paratiróides","Sistema Endócrino","Controlam cálcio e fósforo; essenciais para contração e condução nervosa.", new { Sistema = "Endócrino", Funcoes = new[]{"Cálcio","Fósforo"} }, "Ambos"),
            ("Suprarrenais","Sistema Endócrino","Produzem cortisol, adrenalina e aldosterona; stress e equilíbrio hídrico.", new { Sistema = "Endócrino", Funcoes = new[]{"Stress (HPA)","Equilíbrio hídrico"} }, "Ambos"),

            // Digestivo
            ("Esófago","Sistema Digestivo","Conduz alimento ao estômago; motilidade peristáltica e proteção contra refluxo.", new { Sistema = "Digestivo", Funcoes = new[]{"Condução","Peristaltismo"} }, "Ambos"),
            ("Estômago","Sistema Digestivo","Digestão inicial de proteínas e mistura alimentar; secreção ácida e motilidade.", new { Sistema = "Digestivo", Funcoes = new[]{"Digestão","Quimificação"} }, "Ambos"),
            ("Fígado","Sistema Digestivo","Metaboliza nutrientes, detoxifica e produz bile; central no metabolismo energético.", new { Sistema = "Digestivo", Funcoes = new[]{"Metabolismo","Bile","Detox"} }, "Ambos"),
            ("Vesícula Biliar","Sistema Digestivo","Armazena e concentra bile; emulsificação de gorduras na digestão.", new { Sistema = "Digestivo", Funcoes = new[]{"Armazenar bile","Digestão lipídica"} }, "Ambos"),
            ("Pâncreas","Sistema Digestivo","Função exócrina (enzimas) e endócrina (insulina/glucagon); controlo glicémico.", new { Sistema = "Digestivo", Funcoes = new[]{"Enzimas","Insulina","Glucagon"} }, "Ambos"),
            ("Intestino Delgado","Sistema Digestivo","Grande absorção de nutrientes; segmentos: duodeno, jejuno e íleo.", new { Sistema = "Digestivo", Funcoes = new[]{"Absorção","Digestão"} }, "Ambos"),
            ("Intestino Grosso","Sistema Digestivo","Reabsorção de água e formação de fezes; microbiota relevante.", new { Sistema = "Digestivo", Funcoes = new[]{"Reabsorção","Microbiota"} }, "Ambos"),
            ("Reto","Sistema Digestivo","Segmento terminal para armazenamento e evacuação fecal controlada.", new { Sistema = "Digestivo", Funcoes = new[]{"Armazenamento","Evacuação"} }, "Ambos"),
            ("Ânus","Sistema Digestivo","Esfincteres controlam saída de fezes; continência e sensibilidade perineal.", new { Sistema = "Digestivo", Funcoes = new[]{"Continência","Sensibilidade"} }, "Ambos"),

            // Urinário
            ("Rins","Sistema Urinário","Filtram sangue, regulam eletrólitos e pressão; EPO e vitamina D ativa.", new { Sistema = "Urinário", Funcoes = new[]{"Filtração","Equilíbrio hídrico","EPO"} }, "Ambos"),
            ("Ureteres","Sistema Urinário","Conduzem urina dos rins à bexiga por peristaltismo.", new { Sistema = "Urinário", Funcoes = new[]{"Condução urinária"} }, "Ambos"),
            ("Bexiga","Sistema Urinário","Reservatório de urina com detrusor; coordenação autonómica para micção.", new { Sistema = "Urinário", Funcoes = new[]{"Armazenamento","Micção"} }, "Ambos"),
            ("Uretra (Masculina)","Sistema Urinário","Conduto urinário masculino que também conduz sêmen; atravessa próstata e pénis.", new { Sistema = "Urinário/Reprodutor", Observacoes = "Passa pela próstata", ComprimentoMedioCm = 18 }, "Masculino"),
            ("Uretra (Feminina)","Sistema Urinário","Conduto urinário feminino curto; maior predisposição a infeções ascensionais.", new { Sistema = "Urinário", ComprimentoMedioCm = 4, Risco = "ITU" }, "Feminino"),

            // Reprodutor Masculino
            ("Próstata","Sistema Reprodutor: Masculino","Glândula que contribui para o fluido seminal; envolve porção inicial da uretra.", new { Sistema = "Reprodutor", Funcoes = new[]{"Fluido seminal","Suporte espermático"} }, "Masculino"),
            ("Testículo Esquerdo","Sistema Reprodutor: Masculino","Gónada masculina esquerda; espermatogénese e testosterona.", new { Sistema = "Reprodutor", Funcoes = new[]{"Espermatogénese","Testosterona"} }, "Masculino"),
            ("Testículo Direito","Sistema Reprodutor: Masculino","Gónada masculina direita; papel endócrino e gametogénico.", new { Sistema = "Reprodutor", Funcoes = new[]{"Espermatogénese","Androgénios"} }, "Masculino"),
            ("Epidídimo Esquerdo","Sistema Reprodutor: Masculino","Matura e armazena espermatozoides no testículo esquerdo.", new { Sistema = "Reprodutor", Funcoes = new[]{"Maturação espermática","Armazenamento"} }, "Masculino"),
            ("Epidídimo Direito","Sistema Reprodutor: Masculino","Matura e armazena espermatozoides no testículo direito.", new { Sistema = "Reprodutor", Funcoes = new[]{"Maturação espermática","Armazenamento"} }, "Masculino"),
            ("Ducto Deferente Esquerdo","Sistema Reprodutor: Masculino","Conduz espermatozoides do epidídimo esquerdo à uretra.", new { Sistema = "Reprodutor", Funcoes = new[]{"Condução espermática"} }, "Masculino"),
            ("Ducto Deferente Direito","Sistema Reprodutor: Masculino","Conduz espermatozoides do epidídimo direito à uretra.", new { Sistema = "Reprodutor", Funcoes = new[]{"Condução espermática"} }, "Masculino"),
            ("Vesícula Seminal Esquerda","Sistema Reprodutor: Masculino","Secreções ricas em frutose; contribuem para volume seminal.", new { Sistema = "Reprodutor", Funcoes = new[]{"Fluido seminal","Frutose"} }, "Masculino"),
            ("Vesícula Seminal Direita","Sistema Reprodutor: Masculino","Par homólogo direito; armazenamento parcial do fluido.", new { Sistema = "Reprodutor", Funcoes = new[]{"Fluido seminal","Armazenamento"} }, "Masculino"),
            ("Glândulas de Cowper (Esquerda)","Sistema Reprodutor: Masculino","Glândula bulbouretral esquerda; secreção pré-ejaculatória lubrificante.", new { Sistema = "Reprodutor", Funcoes = new[]{"Lubrificação","Neutralização uretral"} }, "Masculino"),
            ("Glândulas de Cowper (Direita)","Sistema Reprodutor: Masculino","Glândula bulbouretral direita; contribui para o pH e qualidade do sêmen.", new { Sistema = "Reprodutor", Funcoes = new[]{"pH seminal","Lubrificação"} }, "Masculino"),
            ("Pénis","Sistema Reprodutor: Masculino","Órgão copulador e de micção; tecido erétil com corpos cavernosos e esponjoso.", new { Sistema = "Reprodutor", Funcoes = new[]{"Cópula","Micção"} }, "Masculino"),
            ("Corpos Cavernosos (Esquerdo)","Sistema Reprodutor: Masculino","Estrutura erétil par esquerda; enchimento sanguíneo para ereção.", new { Sistema = "Reprodutor", Funcoes = new[]{"Ereção"} }, "Masculino"),
            ("Corpos Cavernosos (Direito)","Sistema Reprodutor: Masculino","Estrutura erétil par direita; componente da rigidez peniana.", new { Sistema = "Reprodutor", Funcoes = new[]{"Ereção"} }, "Masculino"),
            ("Corpo Esponjoso","Sistema Reprodutor: Masculino","Tecido erétil que envolve a uretra peniana; forma a glande distal.", new { Sistema = "Reprodutor", Funcoes = new[]{"Proteção uretral","Glande"} }, "Masculino"),
            ("Escroto","Sistema Reprodutor: Masculino","Bolsa que abriga testículos; termorregulação espermática.", new { Sistema = "Reprodutor", Funcoes = new[]{"Proteção","Termorregulação"} }, "Masculino"),

            // Reprodutor Feminino
            ("Ovário Esquerdo","Sistema Reprodutor: Feminino","Gónada feminina esquerda; foliculogénese e produção hormonal.", new { Sistema = "Reprodutor", Funcoes = new[]{"Ovulação","Estrogénios"} }, "Feminino"),
            ("Ovário Direito","Sistema Reprodutor: Feminino","Gónada feminina direita; secreção hormonal cíclica.", new { Sistema = "Reprodutor", Funcoes = new[]{"Ovulação","Progesterona"} }, "Feminino"),
            ("Trompa de Falópio (Esquerda)","Sistema Reprodutor: Feminino","Conduz óvulo do ovário esquerdo ao útero; local comum de fecundação.", new { Sistema = "Reprodutor", Funcoes = new[]{"Transporte ovular","Fecundação"} }, "Feminino"),
            ("Trompa de Falópio (Direita)","Sistema Reprodutor: Feminino","Conduz óvulo do ovário direito ao útero; secreção nutritiva.", new { Sistema = "Reprodutor", Funcoes = new[]{"Transporte ovular","Secreção"} }, "Feminino"),
            ("Útero","Sistema Reprodutor: Feminino","Órgão de gestação; endométrio cíclico e miométrio contrátil.", new { Sistema = "Reprodutor", Funcoes = new[]{"Gestação","Menstruação","Parto"} }, "Feminino"),
            ("Colo do Útero","Sistema Reprodutor: Feminino","Porção cervical do útero; muco cervical e barreira seletiva.", new { Sistema = "Reprodutor", Funcoes = new[]{"Muco cervical","Barreira"} }, "Feminino"),
            ("Endométrio","Sistema Reprodutor: Feminino","Revestimento uterino cíclico; implantação embrionária e suporte inicial.", new { Sistema = "Reprodutor", Funcoes = new[]{"Implantação","Nutrição embrionária"} }, "Feminino"),
            ("Vagina","Sistema Reprodutor: Feminino","Canal de parto e cópula; microbiota protetora e lubrificação.", new { Sistema = "Reprodutor", Funcoes = new[]{"Cópula","Parto","Proteção"} }, "Feminino"),
            ("Vulva","Sistema Reprodutor: Feminino","Estruturas externas femininas; proteção, prazer e drenagem.", new { Sistema = "Reprodutor", Funcoes = new[]{"Proteção","Prazer"} }, "Feminino"),
            ("Clitóris","Sistema Reprodutor: Feminino","Estrutura erétil altamente inervada; essencial ao prazer sexual.", new { Sistema = "Reprodutor", Funcoes = new[]{"Prazer sexual"} }, "Feminino"),
            ("Mamas (Esquerda)","Sistema Reprodutor: Feminino","Glândula mamária esquerda; lactação e vínculo afetivo materno-infantil.", new { Sistema = "Reprodutor", Funcoes = new[]{"Lactação","Vínculo afetivo"} }, "Feminino"),
            ("Mamas (Direita)","Sistema Reprodutor: Feminino","Glândula mamária direita; leite e proteção imunológica neonatal.", new { Sistema = "Reprodutor", Funcoes = new[]{"Leite materno","Imunidade neonatal"} }, "Feminino"),

            // Outros
            ("Pâncreas Endócrino","Sistema Endócrino","Ilhotas pancreáticas produtoras de insulina e glucagon; homeostase glicémica.", new { Sistema = "Endócrino", Funcoes = new[]{"Insulina","Glucagon"} }, "Ambos"),
            ("Apêndice Vermiforme","Sistema Digestivo","Estrutura linfoide do ceco; possível reservatório de microbiota e vigilância imune.", new { Sistema = "Digestivo", Funcoes = new[]{"Linfoide","Microbiota"} }, "Ambos"),
            ("Pâncreas Exócrino","Sistema Digestivo","Acinares pancreáticos produtores de enzimas; essenciais à digestão.", new { Sistema = "Digestivo", Funcoes = new[]{"Lipases","Proteases"} }, "Ambos"),
        };

        var items = new List<ItemBancoCore>(data.Length);
        foreach (var d in data)
        {
            items.Add(Create(CategoriaCore.Orgao, d.Nome, d.Subcat, d.Desc, d.Meta, fonte, d.Genero));
        }
        return items;
    }

    public static void ValidateAll()
    {
        var items = GetAll();
        var errors = new List<string>();

        Console.WriteLine($"Total itens gerados: {items.Count}");

        // 1) Duplicados
        var dup = items.GroupBy(x => x.ExternalId).Where(g => g.Count() > 1).Select(g => $"{g.Key} ({g.Count()}x)").ToList();
        if (dup.Any()) errors.Add($"❌ GUIDs duplicados: {string.Join(", ", dup)}");
        else Console.WriteLine("✅ Zero GUIDs duplicados");

        // 2) Género correto em órgãos reprodutores
        var generoErrado = items.Where(x => x.Categoria == CategoriaCore.Orgao).Where(x =>
            (x.GeneroAplicavel == null) ||
            (x.Nome.Contains("Próstata", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Masculino") ||
            (x.Nome.Contains("Testículo", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Masculino") ||
            (x.Nome.Contains("Pénis", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Masculino") ||
            (x.Nome.Contains("Cowper", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Masculino") ||
            (x.Nome.Contains("Vesícula Seminal", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Masculino") ||
            (x.Nome.Contains("Ovário", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Feminino") ||
            (x.Nome.Contains("Útero", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Feminino") ||
            (x.Nome.Contains("Vagina", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Feminino") ||
            (x.Nome.Contains("Clitóris", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Feminino") ||
            (x.Nome.Contains("Mama", StringComparison.OrdinalIgnoreCase) && x.GeneroAplicavel != "Feminino")
        ).Select(x => $"{x.Nome} (género: {x.GeneroAplicavel ?? "<null>"})").ToList();
        if (generoErrado.Any()) errors.Add($"❌ Órgãos com género incorreto: {string.Join(", ", generoErrado)}");
        else Console.WriteLine("✅ Órgãos reprodutores com género correto");

        // 3) JsonMetadata
        var semJson = items.Where(x => string.IsNullOrEmpty(x.JsonMetadata)).Select(x => x.Nome).ToList();
        if (semJson.Any()) errors.Add($"❌ Itens sem JsonMetadata: {semJson.Count}");
        else Console.WriteLine("✅ Todos os itens têm JsonMetadata");

        // 4) Totais por categoria
        var totais = items.GroupBy(x => x.Categoria).Select(g => new { Categoria = g.Key, Total = g.Count() }).ToList();
        Console.WriteLine("\n— Totais por Categoria —");
        foreach (var t in totais) Console.WriteLine($"   {t.Categoria}: {t.Total} itens");

        var esperados = new Dictionary<CategoriaCore, int>
        {
            { CategoriaCore.FloraisBach, 38 },
            { CategoriaCore.Chakra, 28 },
            { CategoriaCore.Meridiano, 20 },
        };
        foreach (var (cat, totalEsperado) in esperados)
        {
            var totalReal = totais.FirstOrDefault(x => x.Categoria == cat)?.Total ?? 0;
            if (totalReal != totalEsperado)
                errors.Add($"❌ {cat}: esperados {totalEsperado}, encontrados {totalReal}");
        }

        Console.WriteLine("\n" + new string('=', 60));
        if (errors.Any())
        {
            Console.WriteLine("VALIDAÇÃO FALHOU:\n");
            errors.ForEach(e => Console.WriteLine(e));
            throw new Exception($"Validação falhou com {errors.Count} erro(s)");
        }
        else
        {
            Console.WriteLine("✅✅ Validação completa – dados prontos para uso");
        }
    }
}
